In [1]:
#Day 6 - Feature Engineering & Data Prepration

##Objectives:
#Create new useful features from existing data
#Prepare dataset for analysis and visualization
#Generate business insights ready data

In [3]:
#Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

print("Libraries imported successfully")

Libraries imported successfully

In [4]:
df = pd.read_csv("../data/final_analytical_dataset.csv")

df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_order_count,total_sales,customer_total_spending,delivery_delay_days,delivery_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,4.0,500.0,19.0,8.0,13.0,2,38.71,82.82,-8.0,On Time / Early
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,1.0,400.0,19.0,13.0,19.0,1,141.46,141.46,-6.0,On Time / Early
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,1.0,420.0,24.0,19.0,21.0,1,179.12,179.12,-18.0,On Time / Early
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,3.0,450.0,30.0,10.0,20.0,1,72.20,72.20,-13.0,On Time / Early
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,4.0,250.0,51.0,15.0,15.0,1,28.62,28.62,-10.0,On Time / Early

In [5]:
import os

os.listdir("../data")

['final_analytical_dataset.csv', 'processed', 'raw']

In [ ]:
df.shape

(113425, 26)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 26 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  str
 1   customer_id                    113425 non-null  str
 2   order_status                   113425 non-null  str
 3   order_purchase_timestamp       113425 non-null  str
 4   order_approved_at              113264 non-null  str
 5   order_delivered_carrier_date   111457 non-null  str
 6   order_delivered_customer_date  110196 non-null  str
 7   order_estimated_delivery_date  113425 non-null  str
 8   customer_unique_id             113425 non-null  str
 9   customer_zip_code_prefix       113425 non-null  int64
 10  customer_city                  113425 non-null  str
 11  customer_state                 113425 non-null  str
 12  order_item_id                  112650 non-null  float64
 13  product_id                     112650 non-null  str
 14  seller_id                      112650 non-null  str
 15  shipping_limit_date            112650 non-null  str
 16  price                          112650 non-null  float64
 17  freight_value                  112650 non-null  float64
 18  product_category_name          111047 non-null  str
 19  product_name_lenght            111047 non-null  float64
 20  product_description_lenght     111047 non-null  float64
 21  product_photos_qty             111047 non-null  float64
 22  product_weight_g               112632 non-null  float64
 23  product_length_cm              112632 non-null  float64
 24  product_height_cm              112632 non-null  float64
 25  product_width_cm               112632 non-null  float64
dtypes: float64(10), int64(1), str(15)
memory usage: 22.5 MB

In [11]:
#Convert Date Columns
date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
    'shipping_limit_date'
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')

print("Data columns converted successfully")

Data columns converted successfully

In [ ]:
#Verify Date Types
df[date_columns].dtypes

order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
shipping_limit_date              datetime64[us]
dtype: object

In [ ]:
#Create order Date Features
df['order_year'] = df['order_purchase_timestamp'].dt.year
df['order_month'] = df['order_purchase_timestamp'].dt.month
df['order_month_name'] = df['order_purchase_timestamp'].dt.month_name()
df['order_day_name'] = df['order_purchase_timestamp'].dt.day_name()

df[['order_purchase_timestamp',
    'order_year',
    'order_month',
    'order_month_name',
    'order_day_name']].head()

,order_purchase_timestamp,order_year,order_month,order_month_name,order_day_name
0,2017-10-02 10:56:33,2017,10,October,Monday
1,2018-07-24 20:41:37,2018,7,July,Tuesday
2,2018-08-08 08:38:49,2018,8,August,Wednesday
3,2017-11-18 19:28:06,2017,11,November,Saturday
4,2018-02-13 21:18:39,2018,2,February,Tuesday

In [ ]:
#Delivery Time Feature
df['delivery_time_days'] = (
    df['order_delivered_customer_date'] -
    df['order_purchase_timestamp']
).dt.days

df[['order_purchase_timestamp',
    'order_delivered_customer_date',
    'delivery_time_days']].head()

  order_purchase_timestamp order_delivered_customer_date  delivery_time_days
0      2017-10-02 10:56:33           2017-10-10 21:25:13                 8.0
1      2018-07-24 20:41:37           2018-08-07 15:27:45                13.0
2      2018-08-08 08:38:49           2018-08-17 18:06:29                 9.0
3      2017-11-18 19:28:06           2017-12-02 00:28:42                13.0
4      2018-02-13 21:18:39           2018-02-16 18:17:02                 2.0

In [ ]:
#Create Revenue Features
df['total_sales'] = df['price']+df['freight_value']

df[['price',
    'freight_value',
    'total_sales']].head()

    price  freight_value  total_sales
0   29.99           8.72        38.71
1  118.70          22.76       141.46
2  159.90          19.22       179.12
3   45.00          27.20        72.20
4   19.90           8.72        28.62

In [ ]:
#check revenue statistics
df['total_sales'].describe()

count    112650.000000
mean        140.644059
std         190.724394
min           6.080000
25%          55.220000
50%          92.320000
75%         157.937500
max        6929.310000
Name: total_sales, dtype: float64

In [20]:
#create delivery performance feature
df['delivery_delay_days'] = (
    df['order_delivered_customer_date'] -
    df['order_estimated_delivery_date']
).dt.days

df[['order_delivered_customer_date',
    'order_estimated_delivery_date',
    'delivery_delay_days']].head()

,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days
0,2017-10-10 21:25:13,2017-10-18,-8.0
1,2018-08-07 15:27:45,2018-08-13,-6.0
2,2018-08-17 18:06:29,2018-09-04,-18.0
3,2017-12-02 00:28:42,2017-12-15,-13.0
4,2018-02-16 18:17:02,2018-02-26,-10.0

In [12]:
#customer order count
customer_orders = df.groupby('customer_unique_id')['order_id'].count()

customer_orders.head()

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2    1
0000b849f77a49e4a4ce2b2a4ca5be3f    1
0000f46a3911fa3c0805444483337064    1
0000f6ccb0745a6a4b88665a16c9f078    1
0004aac84e0df4da2b147fca70cf8255    1
Name: order_id, dtype: int64

In [13]:
#Add Order Frequency Feature
df['customer_order_count'] = (
    df.groupby('customer_unique_id')['order_id']
    .transform('count')
)

df[['customer_unique_id',
    'customer_order_count']].head()

                 customer_unique_id  customer_order_count
0  7c396fd4830fd04220f754e42b4e5bff                     2
1  af07308b275d755c9edb36a90c618231                     1
2  3a653a41f6f9fc3d2a113cf8398680e8                     1
3  7c142cf63193a1473d2e66489a9ae977                     1
4  72632f0f9dd73dfee390c9b22eb56dd6                     1

In [18]:
#Customer Total Spending
df['customer_total_spending']=(
    df.groupby('customer_unique_id')['total_sales']
    .transform('sum')
)

df[['customer_unique_id',
    'customer_total_spending']].head()

                 customer_unique_id  customer_total_spending
0  7c396fd4830fd04220f754e42b4e5bff                    82.82
1  af07308b275d755c9edb36a90c618231                   141.46
2  3a653a41f6f9fc3d2a113cf8398680e8                   179.12
3  7c142cf63193a1473d2e66489a9ae977                    72.20
4  72632f0f9dd73dfee390c9b22eb56dd6                    28.62

In [15]:
df.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value',
 'product_category_name',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm',
 'customer_order_count']

In [16]:
df['total_sales'] = df['price'] + df['freight_value']

In [17]:
df[['price','freight_value','total_sales']].head()

    price  freight_value  total_sales
0   29.99           8.72        38.71
1  118.70          22.76       141.46
2  159.90          19.22       179.12
3   45.00          27.20        72.20
4   19.90           8.72        28.62

In [21]:
#Delivery status
df['delivery_status']=np.where(
    df['delivery_delay_days'] <= 0,
    'On Time / Early',
    'Delayed'
)

df[['delivery_delay_days', 'delivery_status']].head()

   delivery_delay_days  delivery_status
0                 -8.0  On Time / Early
1                 -6.0  On Time / Early
2                -18.0  On Time / Early
3                -13.0  On Time / Early
4                -10.0  On Time / Early

In [22]:
#Check Delivery Status Distribution
df['delivery_status'].value_counts()

delivery_status
On Time / Early    102931
Delayed             10494
Name: count, dtype: int64

In [23]:
df.shape

(113425, 31)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 31 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113425 non-null  str
 1   customer_id                    113425 non-null  str
 2   order_status                   113425 non-null  str
 3   order_purchase_timestamp       113425 non-null  datetime64[us]
 4   order_approved_at              113264 non-null  datetime64[us]
 5   order_delivered_carrier_date   111457 non-null  datetime64[us]
 6   order_delivered_customer_date  110196 non-null  datetime64[us]
 7   order_estimated_delivery_date  113425 non-null  datetime64[us]
 8   customer_unique_id             113425 non-null  str
 9   customer_zip_code_prefix       113425 non-null  int64
 10  customer_city                  113425 non-null  str
 11  customer_state                 113425 non-null  str
 12  order_item_id                  112650 non-null  float64
 13  product_id                     112650 non-null  str
 14  seller_id                      112650 non-null  str
 15  shipping_limit_date            112650 non-null  datetime64[us]
 16  price                          112650 non-null  float64
 17  freight_value                  112650 non-null  float64
 18  product_category_name          111047 non-null  str
 19  product_name_lenght            111047 non-null  float64
 20  product_description_lenght     111047 non-null  float64
 21  product_photos_qty             111047 non-null  float64
 22  product_weight_g               112632 non-null  float64
 23  product_length_cm              112632 non-null  float64
 24  product_height_cm              112632 non-null  float64
 25  product_width_cm               112632 non-null  float64
 26  customer_order_count           113425 non-null  int64
 27  total_sales                    112650 non-null  float64
 28  customer_total_spending        113425 non-null  float64
 29  delivery_delay_days            110196 non-null  float64
 30  delivery_status                113425 non-null  str
dtypes: datetime64[us](6), float64(13), int64(2), str(10)
memory usage: 26.8 MB

In [25]:
#SAve Updated Dataset
df.to_csv("../data/final_analytical_dataset.csv",index=False)

print("Day 6 dataset saved successfully")

Day 6 dataset saved successfully

In [6]:
import os

os.makedirs("../data/processed",exist_ok=True)

df.to_csv("../data/processed/ecommerce_merged.csv", index=False)

print("Dataset saved successfully")

Dataset saved successfully